jod.version: 0.0.2

# JOD's IDs
jcp.client.id: test-client-obj
jcp.client.secret: 2d1f9b96-70d3-443b-b21b-08a401ddc16c
jod.obj.id_hw: CSFXX
jod.obj.id_cloud: CSFXX-KETUH-YNKBG
jod.obj.name: 'Config Test Object CSFXX'
jod.permissions.owner: AAAAA-00000-00000

# JCP Client
jcp.connect: false
jcp.url.auth: 'localhost:8998'
jcp.url.apis: 'localhost:9001'

# Communication
#jod.comm.local.enabled: false
jod.comm.cloud.enabled: false

# Executor
jod.executor_mngr.pullers:
  'tstP://com.robypomper.josp.jod.executor.PullerTest'
jod.executor_mngr.listeners:
  'tstL://com.robypomper.josp.jod.executor.ListenerTest
   tstLAdv://com.robypomper.josp.jod.executor.ListenerTestAdv'
jod.executor_mngr.executors:
  'tstE://com.robypomper.josp.jod.executor.ExecutorTest'
