## JCP Client

# JCP_CONNECT_DEF          = "true";
#jcp.connect: 'false'
# JCP_REFRESH_TIME_DEF     = "30";
#jcp.client.refresh: '5'
#jcp.url.apis: api.johnosproject.org:443
jcp.url.apis: 'localhost:9001'
#jcp.url.auth: auth.johnosproject.org:443
jcp.url.auth: 'localhost:8998'
# JCP_CLIENT_ID_DEF        = "";
jcp.client.id: 'test-client-obj'
# JCP_CLIENT_SECRET_DEF    = "";
jcp.client.secret: '2d1f9b96-70d3-443b-b21b-08a401ddc16c'


## JOD Object

# JODOBJ_NAME_DEF          = "";
#jod.obj.name: 'Banana_99'
# JODOBJ_IDCLOUD_DEF       = "";
#jod.obj.id_cloud: 'XXXXX-XXXXX-XXXXX'
# JODOBJ_IDHW_DEF          = "";
#jod.obj.id_hw: 'XXXXX'


## Executors
jod.executor_mngr.pullers:
  'tstP://com.robypomper.josp.jod.executor.PullerTest
   shell://com.robypomper.josp.jod.executor.PullerUnixShell
   http://com.robypomper.josp.jod.executor.impls.http.PullerHTTP'
jod.executor_mngr.listeners:
  'tstL://com.robypomper.josp.jod.executor.ListenerTest
   tstLAdv://com.robypomper.josp.jod.executor.ListenerTestAdv
   file://com.robypomper.josp.jod.executor.ListenerFiles'
jod.executor_mngr.executors:
  'tstE://com.robypomper.josp.jod.executor.ExecutorTest
   shell://com.robypomper.josp.jod.executor.ExecutorUnixShell
   file://com.robypomper.josp.jod.executor.ExecutorFiles
   http://com.robypomper.josp.jod.executor.impls.http.ExecutorHTTP'


## Structure

# JODSTRUCT_PATH_DEF       = "struct.jod";
#jod.structure.path: 'struct.jod'


## Permissions

# JODPERM_PATH_DEF         = "perms.jod";
#jod.permissions.path: 'perms.jod'
# JODPERM_REFRESH_DEF      = "300";
#jod.permissions.refresh: '30'
# JODPERM_GENSTARTEGY_DEF  = "standard";
#jod.permissions.generation_strategy: 'standard'
# JODPERM_OWNER_DEF        = JOSPPerm.WildCards.USR_ANONYMOUS_ID.toString();
jod.permissions.owner: '00000-00000-00000'


## Communication local

# JODCOMM_LOCAL_ENABLED_DEF    = "true";
#jod.comm.local.enabled: 'false'
# JODCOMM_LOCAL_DISCOVERY_DEF = "Auto";
#jod.comm.local.discovery: 'Avahi'
# JODCOMM_LOCAL_PORT_DEF       = "1234";
#jod.comm.local.port: '1234'


## Communication cloud

# JODCOMM_CLOUD_ENABLED_DEF    = "true";
#jod.comm.cloud.enabled: 'false'
