jsl.version: 0.0.2

# JSL's IDs
jcp.client.id: test-client-srv
jcp.client.secret: 88bc8baf-c924-42b9-b691-b2d7c5cec696
jsl.srv.id: test-client-srv
jsl.srv.name: Test Client Srv Awersome!
jsl.usr.id: 3d6bd9ed-8d63-43d6-a465-dbe9029e04c8
jsl.usr.name: pinco
jcp.client.token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1Y2U2Mjg5NS1iNjljLTQ0MmMtYTMwOC04MjA3MTUwZmNmZjMifQ.eyJqdGkiOiJmOThmNDZhNC1kYzU4LTQ2NDktODkwMy0yZGNjNGZkYTQxMjciLCJleHAiOjE1OTA3NTQ5NTcsIm5iZiI6MCwiaWF0IjoxNTkwNzUzMTU3LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4OTk4L2F1dGgvcmVhbG1zL2pjcCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0Ojg5OTgvYXV0aC9yZWFsbXMvamNwIiwic3ViIjoiNjdkZTI3NWMtMTg2MS00ZTg2LThlMDMtMmVmNjQzYzhhNTkyIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InRlc3QtY2xpZW50LXNydiIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6ImQ1YWNlZmU4LTRmMzctNDRmYS05N2FjLTk2NGRjNGZiOTk0ZSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJzcnYiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCByb2xlcyBlbWFpbCBwcm9maWxlIn0.hfCSGJI278CVf7S7s925uL71iWkTxXGx2q4TZY5AInE

# JCP Client
#jcp.connect: false
jcp.url: 'https://localhost:8998'
jcp.client.callback: 'https://localhost:9001'

# Communication
#jsl.comm.local.enabled: false
#jsl.comm.cloud.enabled: false
