jsl.version: 0.0.2

# JSL's IDs
jcp.client.id: test-client-srv
jcp.client.secret: 88bc8baf-c924-42b9-b691-b2d7c5cec696
jsl.srv.id: test-client-srv
jsl.srv.name: Test Client Srv Awersome!

# JCP Client
jcp.connect: true
jcp.url.auth: 'localhost:8998'
jcp.url.apis: 'localhost:9001'
jcp.client.callback: 'https://localhost:9001'

# Communication
#jsl.comm.local.enabled: false
jsl.comm.cloud.enabled: true
#jsl.comm.local.discovery: JmDNS
