{
  jsl.version: 0.0.2,
  jcp.connect: 'true',
  jcp.url: 'https://localhost:8998',
  jcp.client.id: test-client-srv,
  jcp.client.secret: 88bc8baf-c924-42b9-b691-b2d7c5cec696,
  jcp.client.callback: 'https://localhost:9001',
  jsl.srv.id: test-client-srv,
  jsl.srv.name: Test Client Srv
}
