spring.application.name: jcpFrontEnd
server.port: 9002
spring.profiles.active: db, ssl

jsl.version: 2.0.0
jcp.url.apis: localhost:9001
jcp.url.auth: localhost:8998
jcp.client.id: jcp-fe
jcp.client.secret: f379a100-46bb-4fc8-a660-947a98a3afab
jcp.client.callback: https://localhost:8080//apis/user/1.0/login/code/
jsl.srv.id: jcp-fe
jsl.srv.name: JCP FrontEnd
jsl.comm.local.discovery: DNSSD
