oauth2.resource.public-paths: /**

oauth2.url: https://localhost:8998/auth
oauth2.realm: jcp
oauth2.resource: jcpAPIs

oauth2.url_full: ${oauth2.url}/realms/${oauth2.realm}
spring.security.oauth2.resourceserver.jwt.issuer-uri: ${oauth2.url_full}
keycloak.realm: ${oauth2.realm}
keycloak.resource: ${oauth2.resource}
keycloak.auth-server-url: ${oauth2.url}
keycloak.ssl-required: external
keycloak.public-client: false
keycloak.principal-attribute: preferred_username
keycloak.disable-trust-manager: true

jcp.client.id: test-client-api
jcp.client.secret: 20e3f807-f2f8-427d-a048-2462c63bac7f
jcp.urlAPIs: localhost:9001
jcp.urlAuth: localhost:8998
