spring.application.name: jcpAll
server.port: 9000
spring.profiles.active: auth, db-all, ssl
security.require-cors: false

# JCP Clients
jcp.client.ssl.internal: true
jcp.client.ssl.public: true
jcp.client.id: jcp-all
jcp.client.secret: 27e3d70d-5dd0-433e-a85a-40fa4b66d1ad
jcp.client.callback: https://localhost:${server.port}/apis/user/1.0/login/code/
jcp.urlAuth: localhost:8998
jcp.urlAPIs: localhost:9000
#jcp.urlGWs: localhost:9000         # registered via APIs
jcp.urlJSLWebBridge: localhost:9000
jcp.urlFE: localhost:9000

# JCP GWs
jcp.gws.enabled: true
jcp.gws.o2s.url: localhost
jcp.gws.o2s.port: 9101
jcp.gws.o2s.maxClients: 100
jcp.gws.s2o.url: localhost
jcp.gws.s2o.port: 9102
jcp.gws.s2o.maxClients: 100

# JSL Configs
jsl.version: 2.0.0
jcp.url.apis: localhost:9000
jcp.url.auth: localhost:8998
jsl.srv.id: ${jcp.client.id}
jsl.srv.name: JCP FrontEnd
jsl.comm.local.discovery: DNSSD
