spring.application.name: jcpGWs
server.port: 9002
spring.profiles.active: auth, db-apis, ssl

# JCP Clients
jcp.client.ssl: true
jcp.client.id: jcp-gws
jcp.client.secret: 4f5985ac-0e42-4f45-ae74-a859d4fd5184
jcp.urlAuth: localhost:8998
jcp.urlAPIs: localhost:9001
#jcp.urlGWs: localhost:9001         # registered via APIs
jcp.urlJSLWebBridge: localhost:9003
jcp.urlFE: localhost:9004

# JCP GWs
jcp.gws.enabled: true
jcp.gws.s2o.url: localhost:9001
jcp.gws.o2s.url: localhost:9001